apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: default
  labels:
    app: todo-frontend
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
